{
 "title": "Deal with time",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "bucket_interval",
    "query": "1s, 10s, 30s,1m,10m,30m,1h,2h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "venue_type",
    "query": "select distinct val(\"VenueType_id\") from prom_metric.\"Nominal\" where \"time\" >date_trunc('day', now());"
   },
   {
    "name": "way",
    "query": "select distinct val(\"Way_id\") from prom_metric.\"Nominal\" where \"time\" > date_trunc('day', now());"
   },
   {
    "name": "strategy",
    "query": "select distinct val(\"StrategyName_id\") from prom_metric.\"Nominal\" where \"time\" >date_trunc('day', now());"
   },
   { "name": "order_id" },
   {
    "name": "venue_id",
    "query": "select distinct val(\"Venue_id\") from prom_metric.\"Nominal\" where \"time\" >date_trunc('day', now());"
   }
  ]
 },
 "panels": [
  { "title": "Percentile", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Nominal Percentile Table",
   "type": "table",
   "gridPos": { "h": 12, "w": 11, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "targets": [
    {
     "rawSql": "select\r\n       strat,\r\n       bucket,\r\n       round(avg(value)::numeric, 0) avg_in_bucket,\r\n       round(min(value)::numeric, 0) min_in_bucket,\r\n       round(max(value)::numeric, 0) max_in_bucket,\r\n       count(0)\r\nfrom (select val(\"StrategyName_id\") strat,\r\n             value,\r\n             ntile(10) over (order by value) as bucket\r\n      from prom_metric.\"Nominal\"\r\n      where\r\n          ('$order_id' = '' OR val(\"OrderId_id\")='$order_id')\r\n         AND val(\"VenueType_id\") IN ($venue_type)\r\n         AND val(\"Way_id\") IN ($way)\r\n         AND val(\"StrategyName_id\") IN ($strategy)\r\n         AND val(\"Venue_id\") IN ($venue_id)\r\n         --  \"time\" > now() - INTERVAL '1 days'\r\n         AND $__timeFilter(\"time\")\r\n     ) as foo\r\ngroup by strat, bucket\r\norder by bucket;"
    }
   ]
  },
  {
   "title": "Nominal Percentile",
   "type": "barchart",
   "gridPos": { "h": 12, "w": 13, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "targets": [
    {
     "rawSql": "select\r\n       --strat,\r\n       to_char(bucket*10, '999') || '%' AS percentile_label,\r\n       round(avg(value)::numeric, 0) value--,\r\n       --round(min(value)::numeric, 0) min_in_bucket,\r\n       --round(max(value)::numeric, 0) max_in_bucket,\r\n       --count(0)\r\nfrom (select --val(\"StrategyName_id\") strat,\r\n             value,\r\n             ntile(10) over (order by value) as bucket\r\n      from prom_metric.\"Nominal\"\r\n      where\r\n         ('$order_id' = '' OR val(\"OrderId_id\")='$order_id')\r\n           AND val(\"VenueType_id\") IN ($venue_type)\r\n           AND val(\"Way_id\") IN ($way)\r\n           AND val(\"StrategyName_id\") IN ($strategy)\r\n           AND val(\"Venue_id\") IN ($venue_id)\r\n           AND   $__timeFilter(\"time\")\r\n     ) as foo\r\ngroup by /*strat,*/ bucket\r\norder by bucket;"
    }
   ]
  },
  { "title": "Raw data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Deals pure time serie",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "targets": [
    {
     "rawSql": "SELECT time,\r\n    value\r\nFROM prom_metric.\"Nominal\"\r\nWHERE  --\"time\" > now() - INTERVAL '1 days'\r\n     $__timeFilter(\"time\")\r\n     AND ('$order_id' = '' OR val(\"OrderId_id\")='$order_id')\r\n     AND val(\"VenueType_id\") IN ($venue_type)\r\n     AND val(\"Way_id\") IN ($way)\r\n     AND val(\"StrategyName_id\") IN ($strategy)\r\n     AND val(\"Venue_id\") IN ($venue_id)\r\nORDER BY time;"
    }
   ]
  },
  { "title": "Histogram", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Deals Histogram",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "targets": [
    {
     "rawSql": "SELECT time,\r\n    value\r\nFROM prom_metric.\"Nominal\"\r\nWHERE  --\"time\" > now() - INTERVAL '1 days'\r\n     $__timeFilter(\"time\")\r\n     AND ('$order_id' = '' OR val(\"OrderId_id\")='$order_id')\r\n     AND val(\"VenueType_id\") IN ($venue_type)\r\n     AND val(\"Way_id\") IN ($way)\r\n     AND val(\"StrategyName_id\") IN ($strategy)\r\n     AND val(\"Venue_id\") IN ($venue_id)\r\nORDER BY time;"
    }
   ]
  },
  {
   "title": "Norminal distrib every ($bucket_interval) sum",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "targets": [
    {
     "rawSql": "SELECT time_bucket('$bucket_interval', time) AS time,\r\n    SUM(value) sum_nominal\r\nFROM prom_metric.\"Nominal\" srt\r\nWHERE -- symbol = '$symbol' AND\r\n     --\"time\" > now() - INTERVAL '3 days'\r\n     $__timeFilter(\"time\")\r\n     AND ('$order_id' = '' OR val(\"OrderId_id\")='$order_id')\r\n     AND val(\"VenueType_id\") IN ($venue_type)\r\n     AND val(\"Way_id\") IN ($way)\r\n     AND val(\"StrategyName_id\") IN ($strategy)\r\n     AND val(\"Venue_id\") IN ($venue_id)\r\nGROUP BY 1\r\norder by 1;"
    }
   ]
  },
  {
   "title": "[20, 4500] 5 buckets histogram",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "targets": [
    {
     "rawSql": "SELECT val(\"StrategyName_id\") AS strategy, histogram(value, 20, 4500, 5)\r\nFROM prom_metric.\"Nominal\"\r\nwhere --\"time\" > now() - INTERVAL '1 days'\r\n      $__timeFilter(\"time\")\r\n     AND ('$order_id' = '' OR val(\"OrderId_id\")='$order_id')\r\n     AND val(\"VenueType_id\") IN ($venue_type)\r\n     AND val(\"Way_id\") IN ($way)\r\n     AND val(\"StrategyName_id\") IN ($strategy)\r\n     AND val(\"Venue_id\") IN ($venue_id)\r\nGROUP BY \"StrategyName_id\"\r\n;"
    }
   ]
  },
  { "title": "Aggregation", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "by venue_type every $bucket_interval",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "targets": [
    {
     "rawSql": "SELECT time_bucket('$bucket_interval', time) AS time,\r\n    val(\"Way_id\") way,\r\n    val(\"VenueType_id\") venue_type,\r\n    sum(value) sum_nominal\r\nFROM prom_metric.\"Nominal\"\r\nWHERE\r\n      ('$order_id' = '' OR val(\"OrderId_id\")='$order_id')\r\n     AND val(\"VenueType_id\") IN ($venue_type)\r\n     AND val(\"Way_id\") IN ($way)\r\n     AND val(\"StrategyName_id\") IN ($strategy)\r\n     AND val(\"Venue_id\") IN ($venue_id)\r\n      -- \"time\" > now() - INTERVAL '30 minute'\r\n     AND $__timeFilter(\"time\")\r\nGROUP BY 1,2,3\r\norder by 1,2,3"
    }
   ]
  },
  {
   "title": "by venue every $bucket_interval",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "targets": [
    {
     "rawSql": "SELECT time_bucket('$bucket_interval', time) AS time,\r\n    val(\"Venue_id\"),\r\n    sum(value) sum_nominal\r\nFROM prom_metric.\"Nominal\"\r\nWHERE\r\n       --\"time\" > now() - INTERVAL '15 days'\r\n       $__timeFilter(\"time\")\r\n      AND ('$order_id' = '' OR val(\"OrderId_id\")='$order_id')\r\n     AND val(\"VenueType_id\") IN ($venue_type)\r\n     AND val(\"Way_id\") IN ($way)\r\n     AND val(\"StrategyName_id\") IN ($strategy)\r\n     AND val(\"Venue_id\") IN ($venue_id)\r\nGROUP BY 1,2\r\norder by 1,2;"
    }
   ]
  },
  {
   "title": "Strat, VenueCategory",
   "type": "piechart",
   "gridPos": { "h": 15, "w": 9, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "  SELECT\r\n  val(\"StrategyName_id\") as \"Strategy\",\r\n  val(\"VenueCategory_id\") as \"VenueCategory\",\r\n  sum(value)\r\nFROM \"Nominal\"\r\nWHERE\r\n $__timeFilter(\"time\")  \r\n AND ('$order_id' = '' OR val(\"OrderId_id\")='$order_id')\r\n     AND val(\"VenueType_id\") IN ($venue_type)\r\n     AND val(\"Way_id\") IN ($way)\r\n     AND val(\"StrategyName_id\") IN ($strategy)\r\n     AND val(\"Venue_id\") IN ($venue_id)\r\n  group by \"StrategyName_id\",\"VenueCategory_id\""
    }
   ]
  },
  {
   "title": "Strategy, VenueType",
   "type": "table",
   "gridPos": { "h": 15, "w": 14, "x": 9, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "targets": [
    {
     "rawSql": "  SELECT\r\n  val(\"StrategyName_id\") as \"Strategy\",\r\n  val(\"VenueType_id\") as \"VenueType\",\r\n  sum(value)\r\nFROM \"Nominal\"\r\nWHERE\r\n $__timeFilter(\"time\")  \r\n AND ('$order_id' = '' OR val(\"OrderId_id\")='$order_id')\r\n     AND val(\"VenueType_id\") IN ($venue_type)\r\n     AND val(\"Way_id\") IN ($way)\r\n     AND val(\"StrategyName_id\") IN ($strategy)\r\n     AND val(\"Venue_id\") IN ($venue_id)\r\n  group by \"StrategyName_id\",\"VenueType_id\"\r\n  order by sum(value) desc"
    }
   ]
  }
 ]
}